### ISSUE TITLE
Voir si on peut lier le dsfr nomodule avec un lien symbolique plutôt que le copier

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1568]

**Comment by alice-telescoop** [comment]
non ça plante 
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ELOOP: too many symbolic links encountered, stat '/home/alice/telescoop/api-subventions-asso/packages/front/static/dsfr/dsfr.nomodule.min.js'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///home/alice/telescoop/api-subventions-asso/node_modules/vite/dist/node/chunks/dep-68d1a114.js:53803:10)
    at NodeFsHandler._addToNodeFs (file:///home/alice/telescoop/api-subventions-asso/node_modules/vite/dist/node/chunks/dep-68d1a114.js:52620:18) {
  errno: -40,
  code: 'ELOOP',
  syscall: 'stat',
  path: '/home/alice/telescoop/api-subventions-asso/packages/front/static/dsfr/dsfr.nomodule.min.js'
}

```
